<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

<div class="container page-heading" id="contact_heading">
  <!-- <div class="col"> -->
  <div class="">
    <p></p>
    <h1>TERMS OF SERVICE</h1>
  </div>
</div>

<div class="container page-content" id="contact_content">
    <div class="col">
  	<!-- <div class=""> -->
      <p>Welcome to CudiTrader. CudiTrader offers loans to individuals and businesses (collectively, “Borrowers”) who provide bitcoin or ether as collateral (the “Cryptocurrency Secured Loans”). The website at www.CudiTrader.com (the “Site”) and the Cryptocurrency Secured Loans and the various other related services, features, functions, software, applications, websites and networks (together with the Site, collectively, the “CudiTrader Services”) are provided and operated, and are being made available to you, your organization (the “Organization”) and the other Borrowers and users of any of the CudiTrader Services (collectively, “Users”) by Margin Tech International Investments Limited. (“Margin Tech”). All defined terms used herein shall have the meanings prescribed to these terms in these Terms of Service.</p>

	    <p>IMPORTANT! THESE TERMS OF SERVICE (“TERMS”) GOVERN YOUR USE OF THE SITE AND THE OTHER CUDITRADER SERVICES. IF YOU ARE AGREEING TO THESE TERMS ON BEHALF OF YOUR ORGANIZATION, REFERENCES TO “YOU” OR “YOUR” SHALL MEAN YOU, YOUR ORGANIZATION AND ANY OTHER USER ACCESSING AND USING THE SERVICES ON BEHALF OF SUCH ORGANIZATION. BY CLICKING “I AGREE”, DOWNLOADING, USING, CONFIGURING OR ACCESSING THE SITE OR ANY OF THE OTHER CUDITRADER SERVICES OR APPLYING OR RECEIVING A CRYPTOCURRENCY SECURED LOAN OR OTHERWISE SIGNIFYING YOUR ACCEPTANCE OF THESE TERMS, YOU REPRESENT AND WARRANT THAT (A) YOU ARE AUTHORIZED TO ENTER THESE TERMS OF SERVICE FOR AND ON BEHALF OF YOURSELF (AND YOUR ORGANIZATION), AND ARE DOING SO, (B) YOU (AND YOUR ORGANIZATION) CAN LEGALLY ENTER INTO THESE TERMS AND (C) YOU HAVE READ AND UNDERSTAND AND AGREE THAT YOU (AND YOUR ORGANIZATION) SHALL BE BOUND BY THESE TERMS OF SERVICE AND CUDITRADER’S PRIVACY POLICY (HTTP://CUDITRADER.COM/PRIVACY) (THE “PRIVACY POLICY”) AND ALL MODIFICATIONS AND ADDITIONS PROVIDED FOR. IF YOU DO NOT AGREE TO THESE TERMS OF SERVICE OR THE PRIVACY POLICY, PLEASE DO NOT USE ANY OF THE CUDITRADER SERVICES.</p>

<p>In addition to these Terms, if you are approved for a Cryptocurrency Secured Loan, the provision of the Cryptocurrency Secured Loan will be subject to separate agreements including a promissory note and a security agreement and any other agreements you enter into in connection with the Cryptocurrency Secured Loans (as modified from time to time, the “Loan Documents”). If there are any conflicts between these Terms of Service and the Loan Documents, the Loan Documents shall prevail.</p>

<h2>1. ELIGIBILITY</h2>
<p>To access and use the Site and the other CudiTrader Services, including the application for, and receipt of, a Cryptocurrency Secured Loan, you must be at least 18 years of age. By applying or getting a Cryptocurrency Secured Loan, clicking the “I Agree” button or by downloading, installing or otherwise accessing or using any of the CudiTrader Services, you represent that:
<p>●You are at least 18 years old and legally able to form a binding contract with CudiTrader;</p>
<p>●You are a Nigerian citizen and an official resident of the country that you listed (or will list) in connection with your application for a Cryptocurrency Secured Loan;</p>
<p>●You satisfy the eligibility requirements and have not been previously suspended or removed from the Site or any of the other CudiTrader Services or prohibited from applying for or receiving a Cryptocurrency Secured Loan; and</p>
<p>●You will comply with these terms and all applicable local, state, national and international laws, rules and regulations.</p></p>

<h2>2. PRIVACY</h2>
<p>Your privacy is important to CudiTrader. Our goal is to make the CudiTrader Services as good, useful and rewarding for you as possible. In order to do that, CudiTrader may collect and process information from you when you use any of the CudiTrader Services, apply for or receive any Cryptocurrency Secured Loan. CudiTrader will collect certain personally identifiable information from you as set forth in more detail in our Privacy Policy. By applying for or receiving any Cryptocurrency Secured Loan, you agree that CudiTrader may collect, use and disclose, as set forth in the Privacy Policy, the information you provide during your access to or use of any of the CudiTrader Services, and in some cases information that is provided by or through the application for or receipt of any Cryptocurrency Secured Loan. It is important to know that CudiTrader will never sell or rent your personal information to third parties.</p>

<h2>3. ACCESS AND USE RIGHTS; UNAUTHORIZED USE</h2>
<h3>● 3.1 ACCESS AND USE RIGHTS.</h3>
<p>● Subject to your compliance with all the terms and conditions set out in these Terms, CudiTrader hereby grants to you a limited, non-exclusive, non-transferable, freely revocable right to access and use the Site and the other CudiTrader Services to the extent and in accordance with these Terms.</p>
<h3>● 3.2 PREVENTION OF UNAUTHORIZED USE.</h3>
<p>● CudiTrader reserves the right to exercise whatever lawful means it deems necessary to prevent any unauthorized (a) use of any of the CudiTrader or (b) application for, and receipt of, any Cryptocurrency Secured Loans, including, but not limited to, technological barriers, IP mapping, and directly contacting your Internet Service Provider (ISP) regarding such unauthorized use.</p>

<h2>4. CRYPTOCURRENCY SECURED LOANS</h2>
<h3>● 4.1 REGISTRATION.</h3>
<p>● To apply for a Cryptocurrency Secured Loan, you must register and create an account (a “Borrower Account”). You must be a resident of Nigeria to apply for a Cryptocurrency Secured Loan.
If you have any questions or concerns about whether you are located in a country in which we can provide Cryptocurrency Secured Loans, please contact us at info@CudiTrader.com.</p>
<p>● To create and use a Borrower Account, you must provide us with certain information, such as name, date of birth, email address, mailing address and phone number and such other personal and information as may be requested during the registration and account creation process. We may also request a copy of your government-issued identification.</p>
<p>● Except where authorized byCudiTrader, you may not register for more than one Borrower Account, register for a Borrower Account on behalf of an individual other than yourself, operate a Borrower Account on behalf of or for the benefit of any person who is not eligible to register for or operate a Borrower Account in their own name, or register for a Borrower Account on behalf of any group or entity other than your Organization.</p>
<p>● In registering and creating a Borrower Account, you agree to (1) provide true, accurate, current, and complete information about yourself, and, if applicable, your Organization, as prompted during the registration and account creation process “Registration Data”), and (2) maintain and promptly update the Registration Data to keep it true, accurate, current and complete at all times. You are responsible for all activities that occur under your Borrower Account. If you provide any information that is untrue, inaccurate, not current, or incomplete, or CudiTrader has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, CudiTrader has the right to suspend or terminate your account and refuse any and all applications for Cryptocurrency Secured Loans. If any of such information was instrumental in approving your Cryptocurrency Secured Loan, CudiTrader may declare a default under the Loan Documents. You agree not to create a Borrower Account using a false identity or information. You agree not to create a Borrower Account or apply for a Cryptocurrency Secured Loan if you have been previously banned from the CudiTrader Services.</p>

<h3>● 4.2 ADDITIONAL TERMS FOR COMPANY BORROWERS.</h3>
<p>● By applying for Cryptocurrency Secured Loan on behalf of a business or other entity, you represent and warrant that you are duly authorized in accordance with the foregoing by the business or other entity on behalf of which you are acting, that you have the power and authority to enter into binding Loan Documents on behalf of the business or entity or in the capacity in which you are acting, and that the business or entity is in good standing in each jurisdiction in which it is registered to conduct business to the best of your knowledge. Furthermore, you represent and warrant that such business or other entity will abide by all of the terms and conditions of these Terms and any Loan Documents.</p>
<p>If you, the business or entity, any other person acting on behalf of the business or entity violate any of these Terms, or otherwise violate any Loan Document between the business or entity and CudiTrader, CudiTrader may prohibit you, such business or entity and any other person acting on the business or entity’s behalf from using or accessing the CudiTrader Services, including applying for a Cryptocurrency Secured Loan at any time in its sole discretion, with or without notice.</p>
<p>● If you are acting on behalf of a company Borrower, the following additional terms shall apply: 
<p>○ You shall not register for multiple Borrower Accounts on behalf of the same business or entity;</p>
<p>○ You shall not operate or otherwise utilize an account opened in the name of a business or entity for the benefit of any persons other than that business or entity;</p>
<p>○ You shall not operate or otherwise utilize a Borrower Account opened in the name of a business or entity for any purpose prohibited by law or regulation, any activity which that business or entity is not duly authorized to conduct, or for any purpose prohibited by any other agreement between the business or entity and CudiTrader;</p>
<p>○ You shall not operate a Borrower Account on behalf of any business or entity with regard to which you are not an authorized person with the power to enter into binding agreements on behalf of the business or entity;</p>
<p>○ You shall not communicate with any other User regarding the business or entity, or its business operations, or upload, post, transmit, share or otherwise make available any information or informational material identifying the business or entity or its business operations (other than Registration Data provided to CudiTrader or other information requested by CudiTrader or otherwise necessary for your use of the Site or the other CudiTrader Services); and</p>
<p>○ You shall not upload, post, transmit, share, store or otherwise make publicly available on the Site any private information regarding the business or entity, including, without limitation, addresses, phone numbers, email addresses, tax identification numbers and credit, or any personal information regarding persons associated with the business or entity (other than Registration Data provided to CudiTrader).</p></p>
<p>● Furthermore, you represent and warrant and agree, both individually and on behalf of the business or entity, that:
<p>○ all email addresses provided on behalf of the business or entity are and will be used by the business or entity for business purposes; and</p>
<p>○ you will not represent or portray the business or entity as being affiliated with CudiTrader in any capacity other than being a Borrower or User of the Site or other CudiTrader Services without CudiTrader’s prior written consent.</p></p>

<h3>● 4.3 BACKGROUND CHECKS.</h3>
<p>● CudiTrader does not perform credit checks on Borrowers but does conduct full Anti-money Laundering (AML) and Know Your Customer (KYC) verification checks. After providing the necessary information in connection with the creation of your Borrower Account, you hereby authorize CudiTrader to conduct full AML and KYC verification checks.</p>
<h3>● 4.4 CRYPTOCURRENCY COLLATERAL.</h3>
<p>● To secure a Cryptocurrency Secured Loan, you must transfer your bitcoin or ether for collateral (the “Cryptocurrency Collateral”)</p>
<p>● The amount of the Cryptocurrency Secured Loan depends, in part, on the market value of the Cryptocurrency Collateral that you want or can pledge and the loan to market value of the Cryptocurrency Collateral ratio required by CudiTrader (the “Loan to Market Ratio”) (e.g., if CudiTrader requires a loan to market value ratio of 2 to 1, and the market value of the Cryptocurrency Collateral is $100, then the amount of the Cryptocurrency Secured Loan would not exceed $50). If the market value of your Cryptocurrency Collateral decreases below the required Loan to Market Ratio or the ratio specified in your Loan Documents, then you will be required to still pay back just the amount provided as loan.</p>
<p>● You will be required to transfer your Cryptocurrency Collateral to a secure escrow account. When you pay off your Cryptocurrency Secured Loan in full (including interest and any other amounts owing), your Cryptocurrency Collateral will be transferred back to you.</p>
<p>● If you default on the Cryptocurrency Secured Loan or any of the Loan Documents, we may sell some or all of your Cryptocurrency Collateral to repay the Cryptocurrency Secured Loan (including interest and any other amounts owing) in full.</p>

<h3>● 4.5 LOAN DOCUMENTS.<h3>
<p>● After your loan application has been approved, you will be required to execute the Loan Documents. YOU SHOULD READ THE LOAN DOCUMENTS CAREFULLY AND CONSULT WITH LEGAL COUNSEL.</p>
<p>● The Loan Documents are legally binding contracts and they are not negotiable.</p>

<h3>● 4.6 FEES.</h3>
<p>○ (a) Origination Fees. CudiTrader may charge, and you shall pay, an origination fee at the time that the Cryptocurrency Secured Loan proceeds are provided to you (as modified from time to time, the “Origination Fee”). The current Origination Fees will be provided by CudiTrader upon request. The Origination Fee shall be deducted from the Cryptocurrency Secured Loan proceeds.</p>
<p>○ (b) Modification to the Origination Fees and other Fees. Subject to Section 8, CudiTrader may modify the Origination Fee and any other fees in connection with any of the CudiTrader Services (as modified from time to time, collectively, the “Fees”) in its sole discretion.</p>
<p>○ (c) Taxes. To the extent that any taxes are payable by CudiTrader in connection with the Cryptocurrency Secured Loans (other than income or other similar taxes), Borrower shall be obligated to pay to CudiTrader the amount of such taxes in addition to any other amounts owing to CudiTrader.</p>
<p>○ (d) Future Cryptocurrency Secured Loans. In paying any of the Fees, you acknowledge and agree that you are not relying on future availability of any Cryptocurrency Secured Loans.</p>
<p>○ (e) Non-refundable. ALL FEES, INCLUDING THE ORIGINATION FEES, ARE NON-REFUNDABLE, NON-CANCELLABLE AND NON-CREDITABLE UNLESS REQUIRED BY LAW.</p>

<h3>● 4.7 SUPPORT.</h3>
<p>● CudiTrader shall provide technical and other support with respect to the Site and the other CudiTrader Services by phone at (234) 70666 or email at info@cuditrader.com. Support hours are 9:00 am to 5:00 pm GMT, Monday through Friday with the exception of Federal, state and other company holidays.</p>

<h2>5. ADDITIONAL POLICIES</h2>
<p>When using any of the CudiTrader Services, you will be subject to any additional posted policies, guidelines or rules applicable to the Site and the other CudiTrader Services, including Cryptocurrency Secured Loans and features which may be posted from time to time (as added or modified from time to time, the “Policies”). All such Policies are hereby incorporated by reference into these Terms.</p>

<h2>6. RESPECTING OTHER PEOPLE’S RIGHTS</h2>
<p>CudiTrader respects the rights of others and so should you. You therefore may not post or send Content that:
<p>● violates or infringes someone else’s rights of publicity, privacy, copyright, trademark, or other intellectual property right;</p>
<p>● is unlawful, threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another’s privacy, tortious, obscene, vulgar, pornographic, offensive, profane, contains or depicts nudity, contains or depicts sexual activity, or is otherwise inappropriate as determined by CudiTrader in its sole discretion;</p>
<p>● is false, misleading, untruthful or inaccurate; ● includes anyone’s identification documents or sensitive financial information</p>
<p>● impersonates any person or entity, including any of CudiTrader’s employees or representatives; or</p>
<p>● spams or solicits any Users, including any other Borrowers.</p>
</p>

<h2>7. ACCOUNT SECURITY</h2>
<p>When you access and use any of the CudiTrader Services, or apply for or receive any Cryptocurrency Secured Loans, you may be asked to provide a password. You are solely responsible for maintaining the confidentiality of your account and password and for restricting access to your computer and mobile devices, and you agree to accept responsibility for all activities that occur under your account or password. You agree that the information you provide to CudiTrader on registration and at all other times will be true, accurate, current, and complete. You also agree that you will ensure that this information is kept accurate and up-to-date at all times.</p>
<p>If you change or deactivate the email that you used to create an CudiTrader account, you must update your account information within 72 hours to prevent us from sending to someone else messages intended for you.</p>
<p>If at any time you have reason to believe that your account is no longer secure (e.g., in the event of a loss, theft or unauthorized disclosure or use of your account ID or password), then you shall immediately notify CudiTrader at info@Cuditrader.com. You may be liable for the losses incurred by CudiTrader or others due to any unauthorized use of your account or any of the CudiTrader Services.</p>

<h2>8. MODIFICATION OF THESE TERMS</h2>
<p>CudiTrader reserves the right, at its sole discretion, to change, modify, add, or remove portions of these Terms at any time by posting the amended Terms to the Site or otherwise through the CudiTrader Services. If CudiTrader updates these Terms, it will update the “last updated” date at the top of the Terms. Please check these Terms, including any Policies, periodically for changes. Your continued use of the CudiTrader Services or application for a Cryptocurrency Secured Loan after the posting of changes constitutes your binding acceptance of such changes. In the event that a change to these Terms materially modifies your rights or obligations (including applicable Fees), CudiTrader will make reasonable efforts to notify you of such change. CudiTrader may provide notice through a pop-up or banner within any of the CudiTrader Services, by sending an email to any address you may have used to register for an account, or through other similar mechanisms. Additionally, if the changed Terms materially modify your rights or obligations, CudiTrader may require you to provide consent by accepting the changed Terms. If CudiTrader requires your acceptance of the changed Terms, changes are effective only after your acceptance. For all other changes, except as stated elsewhere by CudiTrader, such amended Terms or Fees will automatically be effective, replacing the previously-effective Terms or Fees, thirty (30) days after they are initially posted on any of the CudiTrader Services.</p>
<p>IF AT ANY TIME YOU DO NOT AGREE TO THESE TERMS, PLEASE IMMEDIATELY TERMINATE YOUR USE OF ALL CUDI TRADER SERVICES.</p>
<p>To the extent that any modifications to the Terms or Policies are not allowed under applicable laws, the prior most recent version of the Terms or Policies shall continue to apply.</p>

<h2>9. TESTIMONIALS AND OTHER COMMENTS</h2>
<p>CudiTrader may now or in the future request or permit the submission of testimonials and other comments (in the form of written comments or voice or video recordings) regarding the Cryptocurrency Secured Loans and the other CudiTrader Services (collectively, the “Testimonials”). If you submit any Testimonials, CudiTrader shall own and have the unrestricted right to use any Testimonials (and your name in connection with such Testimonials) without restriction or payment of any kind to you, including the right to display, distribute and otherwise exploit your Testimonial and name for advertising and other purposes.</p>

<h2>10. PROHIBITED CONDUCT</h2>
<p>BY USING ANY OF THE CUDI TRADER SERVICES OR APPLYING FOR A CRYPTOCURRENCY SECURED LOAN, YOU AGREE NOT TO:</p>
<h3>● 10.1</h3>
<p>● Decipher, decompile, disassemble, reverse engineer, modify, translate, reverse engineer or otherwise attempt to derive source code, algorithms, tags, specifications, architectures, structures or other elements of any of the CudiTrader Services, in whole or in part (except to the extent that the laws of your jurisdiction make such restrictions unenforceable);</p>
<h3>● 10.2</h3>
<p>● Use any of the CudiTrader Services for the benefit of anyone other than your Organization or you, including selling, reselling, distributing, hosting, leasing, renting, licensing or sublicensing, in whole or in part, any of the CudiTrader Services, for hosting or time-sharing services, or as part of a service bureau or outsourcing offering;</p>
<h3>● 10.3</h3>
<p>● Provide any services to any third party using any of the CudiTrader Services except in accordance with these Terms;</p>
<h3>● 10.4</h3>
<p>● Prepare any derivative work of any of the CudiTrader Services, or any other program based upon any of the CudiTrader Services;</p>
<h3>● 10.5</h3>
<p>● Reproduce, modify, adapt, translate or otherwise make any changes to any of the CudiTrader Services or any part thereof;</p>
<h3>● 10.6</h3>
<p>● Copy, disclose, or distribute any data available on or through any of the CudiTrader Services or Cryptocurrency Secured Loan, in any medium, including without limitation, by any automated or non-automated “screen scraping,” “database scraping” or any other activity with the purpose of obtaining content or other information;</p>
<h3>● 10.7</h3>
<p>● Interfere with, circumvent or disable any security or other technological features or measures of any of the CudiTrader Services or attempt to gain unauthorized access to any of the CudiTrader Services or its related systems or networks;</p>
<h3>● 10.8</h3>
<p>● Make unsolicited offers, advertisements, or proposals, or send junk mail or spam to other Users (including any Borrowers) of any of the CudiTrader Services (including, but not limited to, unsolicited advertising, promotional materials or other solicitation material, bulk mailing of commercial advertising, chain mail, informational announcements, charity requests, and petitions for signatures);</p>
<h3>● 10.9</h3>
<p>● Use bots or other automated methods to: access any of the CudiTrader Services send or redirect messages or perform any other activities through any of the CudiTrader Services;</p>
<h3>● 10.10</h3>
<p>● Use any of the CudiTrader Services or the Cryptocurrency Secured Loans for any unlawful or inappropriate activities, such as gambling, obscenity, pornography, violence, transmission of deceptive messages, or harassment;</p>
<h3>● 10.11</h3>
<p>● Engage in “framing,” “mirroring,” or otherwise simulating the appearance or function of any of the CudiTrader Services or place pop-up windows over the Site’s pages;</p>
<h3>● 10.12</h3>
<p>● Take any action that imposes, or may impose at CudiTrader’s sole determination, an unreasonable or disproportionately large load on CudiTrader’s infrastructure;</p>
<h3>● 10.13</h3>
<p>● Deep-link to any of the CudiTrader Services without CudiTrader’s consent; or</p>
<h3>● 10.14</h3>
<p>● Share or disclose information of others without their express consent.</p>

<h2>11. THIRD PARTY SITES</h2>
<p>The CudiTrader Services may include links or references to other web sites or services (“Third Party Sites”) solely as a convenience to Users. CudiTrader does not endorse any such Third-Party Sites or the information, materials, products, or services contained on or accessible through Third Party Sites. In addition, your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Site or any of the other CudiTrader Services are solely between you and such advertiser. Access and use of Third Party Sites, including the information, materials, products, and services on or available through Third Party Sites are solely at your own risk.</p>

<h2>12. MOBILE AND DATA CHARGES</h2>
<p>You are responsible for any mobile and data charges that you may incur for using any of the CudiTrader Services, including text-messaging charges. If you’re unsure what those charges may be, you should ask your service provider before using the CudiTrader Services or the Cryptocurrency Secured Loans.</p>

<h2>13. TERMINATION; TERMS OF SERVICE VIOLATIONS</h2>
<h3>● 13.1 CUDITRADER.</h3>
<p>● You agree that CudiTrader, in its sole discretion, for any or no reason, and without penalty, may suspend or terminate your use of the CudiTrader Services or any Borrower Account you may have with CudiTrader and remove and discard all or any part of your account, user profile, and any Content, at any time.</p>
<p>CudiTrader may also in its sole discretion and at any time prohibit any application for Cryptocurrency Secured Loans. You agree that any suspension or termination of your access to the CudiTrader Services or any account you may have or ability to apply for a Cryptocurrency Secured Loan may be effected without prior notice, and you agree that CudiTrader will not be liable to you or any third party for any such termination.</p>
<p>CudiTrader reserves the right to fully cooperate with any law enforcement authorities or court order requesting or directing CudiTrader to disclose the identity of anyone posting any e-mail messages, or publishing or otherwise making available any materials that are believed to violate these Terms. Any suspected fraudulent, abusive or illegal activity may be referred to appropriate law enforcement authorities. These remedies are in addition to any other remedies CudiTrader may have at law or in equity. As discussed herein, CudiTrader does not permit copyright infringing activities on the Site or any of the other CudiTrader Services, and shall be permitted to terminate access to any of the CudiTrader Services, and remove all Content or other content submitted by any Users who are found to be repeat infringers. BY ACCEPTING THESE TERMS, YOU WAIVE AND SHALL HOLD CUDI TRADER HARMLESS FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY CUDI TRADER DURING OR AS A RESULT OF ITS INVESTIGATIONS AND/OR FROM ANY ACTIONS TAKEN AS A CONSEQUENCE OF INVESTIGATIONS BY EITHER CUDI TRADER OR LAW ENFORCEMENT AUTHORITIES.</p>
<h3>● 13.2 YOU.</h3>
<p>● Your only remedy against CudiTrader with respect to any dissatisfaction with (i) the Site or the other CudiTrader Services, including the Cryptocurrency Secured Loans, (ii) any term of these Terms, (iii) any policy or practice of CudiTrader in operating the CudiTrader Services, or (iv) any Content transmitted through any of these CudiTrader Services or the application process for a Cryptocurrency Secured Loan, is to terminate your Borrower Account and your use of all of the CudiTrader Services. You may terminate your use of the CudiTrader Services and your Borrower account at any time.</p>
<p>After such termination, you must refrain from use of the CudiTrader Services until authorized by CudiTrader. Notwithstanding the foregoing, your termination of your account or your use of any of the CudiTrader Services shall not affect in any way your obligations under any Loan Documents that are still in effect.</p>

<h2>14. OWNERSHIP; PROPRIETARY RIGHTS</h2>
<p>The Site and the other CudiTrader Services are owned and operated by CudiTrader. The visual interfaces, graphics, design, compilation, information, computer code (including source code or object code), products, software, services, and all other elements of the CudiTrader Services provided by CudiTrader (the “Materials”) are protected by Nigeria’s copyright, trade dress, patent, and trademark laws, international conventions, and all other relevant intellectual property and proprietary rights, and applicable laws. Except for any Content that are provided and owned by Users, all Materials contained on any of the CudiTrader Services are the property of CudiTrader or its subsidiaries or affiliated companies and/or third-party licensors. All trademarks, service marks, and trade names are proprietary to CudiTrader or its affiliates and/or third-party licensors. Except as expressly authorized by CudiTrader, you agree not to sell, license, distribute, copy, modify, publicly perform or display, transmit, publish, edit, adapt, create derivative works from, or otherwise make unauthorized use of the Materials. CudiTrader reserves all rights not expressly granted in these Terms.
CudiTrader shall own and have the unrestricted right to use or act upon any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by you or any other party relating to any of the CudiTrader Services, including the Cryptocurrency Secured Loans, without restriction or payment of any kind to you.</p>

<h2>15. CONSENT TO ELECTRONIC TRANSACTIONS AND DISCLOSURES</h2>
<h3>● 15.1 INTERNET OPERATIONS.</h3>
<p>● CudiTrader operates principally on the Internet (although there may be some direct communications, e.g., by phone), so if you want to apply for a Cryptocurrency Secured Loan or otherwise use any of the CudiTrader Services, it is necessary for you to consent to transact business with us online and electronically. As part of doing business with us, therefore, we also need you to consent to our giving you certain disclosures electronically, either via our Site or to the email address you provide to us. By agreeing to these Terms of Service, you agree to receive electronically all documents, communications, notices, contracts, and agreements, including the Loan Documents, arising from or relating to your use of the Site and the other CudiTrader Services, including any Cryptocurrency Secured Loans you apply for or receive, your registration as a borrower, the servicing of your Cryptocurrency Secured Loan, (each, a “Disclosure”), from us. The decision to do business with us electronically is yours. This Section 16 informs you of your rights concerning Disclosures.</p>
<h3>● 15.2 COMMUNICATIONS.</h3>
<p>● By accepting these Terms, you expressly consent to be contacted by us, our agents, representatives, affiliates, or anyone calling on our behalf for any and all purposes in connection with the CudiTrader Services, including any Cryptocurrency Secured Loans (and not for spam), at any telephone number, or physical or electronic address you provide, at which you may be reached or numbers or addresses we can reasonably associate with your account (through skip trace, caller ID capture or other means), including by SMS messages (including text messages), Telegram ID and calls and messages (including prerecorded and artificial voice and autodialed).</p>
<p>Automated messages may be played when the telephone is answered, whether by you or someone else. In the event that an agent or representative calls, he or she may also leave a message on your answering machine, voice mail, or send one via text. You certify, warrant and represent that the telephone numbers and addresses that you have provided to us are your numbers and addresses and not someone else’s. You represent that you are permitted to receive calls at each of the telephone numbers you have provided to us. You agree to alert us whenever you stop using a particular telephone number.</p>
<h3>● 15.3 CALL RECORDING AND MONITORING.</h3>
<p>● You consent to the recording and monitoring, for quality assurance, training, risk management and/or collection purposes, of any call that you place with us (or our agents, representatives, affiliates, third parties or anyone calling on our behalf) or that we (or our agents, representatives, affiliates, third parties or anyone calling on our behalf) place to you.</p>
<h3>● 15.4 ELECTRONIC COMMUNICATIONS.</h3>
<p>● Any Disclosures will be provided to you electronically through either our Site or via electronic mail to the email address you provided. If you require paper copies of such Disclosures, you may sign in to your account on our Site and print the documents desired. We may discontinue electronic provision of Disclosures at any time in our sole discretion.</p>
<h3>● 15.5 SCOPE OF CONSENT.</h3>
<p>● Your consent to receive Disclosures and transact business electronically, and your agreement to do so, applies to any transactions to which such Disclosures relate, between you and CudiTrader. Your consent will remain in effect for so long as you are a User and, if you are no longer a User, will continue until such a time as all Disclosures relevant to transactions that occurred while you were a User have been made.</p>
<h3>● 15.6 ABILITY TO DO BUSINESS ELECTRONICALLY.</h3>
<p>● Before you decide to do business electronically with CudiTrader, you should consider whether you have the required hardware and software capabilities necessary to access and use the CudiTrader Services and to receive the Disclosures. It is your responsibility to determine and ensure that you have the hardware and software to access and use the CudiTrader Services and to receive the Disclosures.</p>
<h3>● 15.7 WITHDRAWING CONSENT.</h3>
<p>● You may withdraw your consent to receive Disclosures electronically by contacting us at INFO@Cuditrader.com. If you have a pending a Cryptocurrency Secured Loan application on our Site we will terminate it and remove it from our system. If you have already received a Cryptocurrency Secured Loan, all consents will remain in effect, and we will send Disclosures to your verified home address provided during registration.</p>
<h3>● 15.8 ELECTRONIC SIGNATURES</h3>
<p>● You agree that (a) any Disclosures that require a signature, including the Loan Documents, may be electronically signed and (b) the electronic signatures appearing on any of the Disclosures, are the same as handwritten signatures for the purposes of validity, enforceability and admissibility.</p>
<h3>● 15.9 HOW TO CONTACT US REGARDING ELECTRONIC DISCLOSURES.</h3>
<p>● You can contact us via email at Info@CudiTrader.com. You may also reach us in writing to us at the following address: Margin Tech International Investments LImited, 3, Segun Maru Street Magodo estate, Lagos State, Nigeria, Attention: Legal Support. You should print a copy of these Terms for your records and you agree and acknowledge that you can access, receive and retain all Disclosures electronically sent via email or posted on the Site.</p>

<h2>16. INDEMNIFICATION</h2>
<p>You agree to indemnify, save, and hold CudiTrader, its affiliated companies, contractors, employees, agents and its third-party suppliers, licensors, and partners harmless from any claims, losses, damages, liabilities, including legal fees and expenses, arising out of your use or misuse of the Site or any of the other CudiTrader Services or any of the Content, any application for or receipt of any Cryptocurrency Secured Loan, any violation by you of these Terms, any breach of the representations, warranties, and covenants made by you herein or paying any Fees. CudiTrader reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify CudiTrader, and you agree to cooperate with CudiTrader’s defense of these claims. CudiTrader will use reasonable efforts to notify you of any such claim, action, or proceeding upon becoming aware of it.</p>

<h2>17. WARRANTIES; DISCLAIMERS</h2>
<h3>● 17.1 WARRANTIES.</h3>
<p>● CudiTrader represents and warrants that:

<p>○ (a) the CudiTrader Services will be performed in a professional and workmanlike manner in accordance with these terms and consistent with applicable industry standards.</p></p>
<h3>● 17.2 LIMITATION OF WARRANTIES.</h3>
<p>● TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, AND EXCEPT AS SET FORTH IN SECTION 17.1, CUDI TRADER AND ITS AFFILIATES, CONTRACTORS, DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, THIRD-PARTY PARTNERS, LICENSORS AND SUPPLIERS (COLLECTIVELY, THE “CUDI TRADER PARTIES”) DISCLAIM ALL WARRANTIES, STATUTORY, EXPRESS OR IMPLIED WITH RESPECT TO THE SITE, THE OTHER CUDI TRADER SERVICES AND THE CRYPTOCURRENCY SECURED LOANS, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS AND WARRANTIES ARISING FROM A COURSE OF DEALING, USAGE OR TRADE PRACTICE. WITHOUT LIMITATION TO THE FOREGOING, CUDI TRADER PROVIDES NO WARRANTY OR UNDERTAKING, AND MAKES NO REPRESENTATION OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, THAT THE CUDI TRADER SERVICES OR THE CRYPTOCURRENCY SECURED LOANS, WILL MEET YOUR REQUIREMENTS OR ACHIEVE ANY INTENDED RESULTS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE CUDI TRADER PARTIES OR THROUGH THE SITE OR THE OTHER CUDI TRADER SERVICES OR THE CRYPTOCURRENCY SECURED LOANS WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN.</p>
<h3>● 17.3 “AS IS” AND “AS AVAILABLE” AND “WITH ALL FAULTS”.</h3>
<p>● YOU EXPRESSLY AGREE THAT THE USE OF ANY OF THE CUDI TRADER SERVICES, AND ANY DATA, ASSESSMENTS, RESULTS, INFORMATION, THIRD-PARTY SOFTWARE, CONTENT, THIRD PARTY SITES, SERVICES, OR APPLICATIONS MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH ANY OF THE CUDI TRADER ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE”, “WITH ALL FAULTS” BASIS AND WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND EITHER EXPRESS OR IMPLIED.</p>
<h3>● 17.4 PLATFORM OPERATION AND CONTENT.</h3>
<p>● THE CUDI TRADER PARTIES DO NOT WARRANT THAT THE DATA, ASSESSMENTS, RESULTS, CONTENT, FUNCTIONS, OR ANY OTHER INFORMATION OFFERED ON OR THROUGH ANY OF THE CUDI TRADER SERVICES, OR ANY THIRD-PARTY SITES WILL BE UNINTERRUPTED, OR FREE OF ERRORS, VIRUSES OR OTHER HARMFUL COMPONENTS AND DO NOT WARRANT THAT ANY OF THE FOREGOING WILL BE CORRECTED.</p>
<h3>● 17.5 ACCURACY.</h3>
<p>● EXCEPT AS SPECIFICALLY PROVIDED IN WRITING BY CUDI TRADER, THE CUDI TRADER PARTIES DO NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF ANY OF THE CUDI TRADER SERVICES THE OR ANY THIRD-PARTY SITES IN TERMS OF CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE.</p>
<h3>● 17.6 HARM TO YOUR COMPUTER.</h3>
<p>● YOU UNDERSTAND AND AGREE THAT YOU USE, ACCESS, DOWNLOAD, OR OTHERWISE OBTAIN INFORMATION, MATERIALS, ASSESSMENTS, RESULTS OR DATA THROUGH ANY OF THE CUDI TRADER SERVICES OR ANY THIRD-PARTY SITE, AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY (INCLUDING YOUR COMPUTER SYSTEM) OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OR USE OF SUCH MATERIAL OR DATA.</p>
<h3>● 19.7 NOT AN EXCHANGE, ADMNISTRATOR OR ISSUER OF VIRTUAL CURRENCY.</h3>
<p>● CUDI TRADER IS NOT AN EXCHANGE, ADMISTRATOR OR ISSUER OF VIRTUAL CURRENCY OR BANK, BROKER DEALER, INVESTMENT CLUB, OR INVESTMENT ADVISOR, BUT RATHER A PLATFORM THROUGH WHICH BORROWERS CAN USE THEIR BITCOIN OR ETHER AS COLLATERAL FOR LOANS. BORROWERS SHALL BE SOLELY RESPONSIBLE FOR COMPLIANCE WITH ALL APPLICABLE U.S. AND INTERNATIONAL LAWS AND REGULATIONS RELATING TO THE USE OF BITCOIN AND/OR ETHER. EACH OF THE BORROWERS AND OTHER USERS OF THE CUDI TRADER SERVICES SHALL INDEMNIFY CUDI TRADER FOR ALL CLAIMS, LOSSES, DAMAGES, LIABILITIES, INCLUDING LEGAL FEES AND EXPENSES, ARISING OUT OF OR RELATED TO THE USE OF BITCOIN AND/OR ETHER AS COLLATERAL, INCLUDING THE VIOLATION (WHETHER INTENTIONAL OR NOT) OF ANY APPLICABLE NIGERIAN OR INTERNATIONAL LAWS.</p>

<h2>18. LIMITATION OF LIABILITY AND DAMAGES</h2>
<h3>● 18.1 LIMITATION OF LIABILITY</h3>
<p>● UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, WILL THE CUDI TRADER PARTIES BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, PUNITIVE, RELIANCE, OR EXEMPLARY DAMAGES (INCLUDING WITHOUT LIMITATION DAMAGES ARISING FROM ANY UNSUCCESSFUL COURT ACTION OR LEGAL DISPUTE, LOST BUSINESS, LOST REVENUES OR LOSS OF ANTICIPATED PROFITS OR ANY OTHER PECUNIARY OR NON-PECUNIARY LOSS OR DAMAGE OF ANY NATURE WHATSOEVER) ARISING OUT OF OR RELATING TO THESE TERMS OR THAT RESULT FROM YOUR USE OR YOUR INABILITY TO USE OF THE SITE OR THE OTHER CUDI TRADER SERVICES, OR APPLICATION FOR ANY CRYPTOCURRENCY SECURED LOAN OR ANY OTHER INTERACTIONS WITH CUDI TRADER, EVEN IF CUDI TRADER OR A CUDI TRADER AUTHORIZED REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IN SUCH CASES, CUDI TRADER’S LIABILITY WILL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.</p>
<h3>● 19.2 LIMITATION OF DAMAGES.</h3>
<p>● IN NO EVENT WILL THE CUDI TRADER PARTIES’ TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE SITE AND THE OTHER CUDI TRADER, INCLUDING THE APPLICATION OR RECEIPT OF ANY CRYPTOCURRENCY SECURED LOAN, OR YOUR INTERACTION WITH OTHER USERS (WHETHER IN CONTRACT, TORT INCLUDING NEGLIGENCE, WARRANTY, OR OTHERWISE), EXCEED THE GREATER OF (A) $50 AND (B) THE FEES PAID BY YOU, IF ANY, TO CUDI TRADER DURING THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE DATE OF THE CLAIM, WHICHEVER IS GREATER. Nothing in this Section 19.2 is intended to limit our responsibility or liability to you with respect to any Cryptocurrency Collateral or to the return of your Cryptocurrency Collateral after your Cryptocurrency Secured Loan (and any interest and other amounts owing) has been paid in full.</p>
<h3>● 19.3 RELEASE FOR DISPUTES BETWEEN USERS.</h3>
<p>● If you have a dispute with any other Users or other third parties, you hereby release CudiTrader and the other CudiTrader Parties from claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such disputes.</p>
<h3>● 18.4 THIRD PARTY SITES.</h3>
<p>● THESE LIMITATIONS OF LIABILITY ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY YOU BY REASON OF ANY PRODUCTS OR SERVICES SOLD OR PROVIDED ON ANY THIRD-PARTY SITES OR OTHERWISE BY THIRD PARTIES OTHER THAN CUDI TRADER AND RECEIVED THROUGH OR ADVERTISED ON ANY OF THE CUDI TRADER SERVICES OR RECEIVED THROUGH ANY THIRD-PARTY SITES.</p>
<h3>● 18.5 BASIS OF THE BARGAIN.</h3>
<p>● YOU ACKNOWLEDGE AND AGREE THAT CUDI TRADER HAS OFFERED THE CUDI TRADER SERVICES AND THE CRYPTOCURRENCY SECURED LOANS, SET ITS PRICES, AND ENTERED INTO THESE TERMS IN RELIANCE UPON THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH HEREIN, THAT THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH HEREIN REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN YOU AND CUDI TRADER, AND THAT THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH HEREIN FORM AN ESSENTIAL BASIS OF THE BARGAIN BETWEEN YOU AND CUDI TREADER. CUDI TRADER WOULD NOT BE ABLE TO PROVIDE ANY OF THE CUDI TRADER SERVICES OR THE CRYPTOCURRENCY SECURED LOANS TO YOU ON AN ECONOMICALLY REASONABLE BASIS WITHOUT THESE LIMITATIONS.</p>

<h2>19. MISCELLANEOUS</h2>
<h3>● 19.1 NOTICE.</h3>
<p>● CudiTrader may provide you with notices, including those regarding changes to these Terms, by email, regular mail or postings on any of the CudiTrader Services. Notice will be deemed given twenty-four hours after the email is sent, unless CudiTrader is notified that the email address is invalid.</p>
<p>Alternatively, CudiTrader may give you legal notice by mail to a postal address, if provided by you through any of the CudiTrader Services. In such case, notice will be deemed given three days after the date of mailing. Notice posted on any of the CudiTrader Services is deemed given 30 days following the initial posting.</p>
<h3>● 19.2 WAIVER.</h3>
<p>● The failure of CudiTrader to exercise or enforce any right or provision of these Terms or under any of the Loan Documents will not constitute a waiver of such right or provision. Any waiver of any provision of these Terms or any of the Loan Documents will be effective only if in writing and signed by CudiTrader.</p>
<h3>● 19.3 DISPUTE RESOLUTION.</h3>
<p>● If a dispute arises between you and CudiTrader, the goal is to provide you with a neutral and cost-effective methods of resolving the dispute quickly. Accordingly, you and CudiTrader agree that any dispute, claim or controversy at law or equity that arises out of these Terms, the Site or any of the other CudiTrader Services, or any Cryptocurrency Secured Loan (a “Dispute”) will be resolved in accordance with this Section 19.3 or as CudiTrader and you otherwise agree in writing. Before resorting to these dispute methods, CudiTrader strongly encourages you to first contact CudiTrader directly to seek a resolution.</p>
<p>● The parties hereby irrevocably and unconditionally agree that service of process in any such Dispute may be effected by mailing a copy of such process by certified mail, postage prepaid, to such party at the address provided by such party.
<p>○ (A) Choice of Law. THESE TERMS SHALL BE GOVERNED IN ALL RESPECTS BY THE LAWS OF THE STATE OF LAGOS, NIGERIA.</p>
<p>○ (B) Improperly Filed Disputes. All claims you bring against CudiTrader must be resolved in accordance with this Section 19.3. All claims filed or brought contrary to this Section 19.3 shall be considered improperly filed. Should you file a claim contrary to this Section 19.3, CudiTrader may recover attorneys’ fees and costs up to 15,000,000 Naira, provided that CudiTrader has notified you in writing of the improperly filed claim, and you have failed to promptly withdraw the claim.</p>
<p>○ (C) Prevailing Party. In the event that either party institutes any legal suit, action or proceeding against the other party arising out of or relating to these Terms, the Privacy Policy, or any of the CudiTrader Services, or any Cryptocurrency Secured Loan, the prevailing party in the suit, action or proceeding shall be entitled to receive in addition to all other damages to which it may be entitled, the costs incurred by such party in conducting the suit, action or proceeding, including reasonable attorneys’ fees and expenses and court costs.</p>
<p>○ (D) LIMITATION ON TIME TO FILE CLAIMS. ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS, THE PRIVACY POLICY, ANY OF THE CUDI TRADER SERVICES, ANY CRYPTOCURRENCY SECURED LOAN, ANY PRODUCT OR OTHER SERVICES, ANY CONTENT OR YOUR RELATIONSHIP WITH CUDI TRADER MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES, OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED.</p>
</p>
<h3>● 19.4 SEVERABILITY.</h3>
<p>● If any provision of these Terms (including the Privacy Policy or any Policies) is held to be unlawful, void, or for any reason unenforceable, then that provision will be limited or eliminated from these Terms to the minimum extent necessary and will not affect the validity and enforceability of any remaining provisions.</p>
<h3>● 19.5 ASSIGNMENT.</h3>
<p>● These Terms and related Policies, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by CudiTrader without restriction. Any assignment attempted to be made in violation of these Terms shall be void.</p>
<h3>● 19.6 SURVIVAL.</h3>
<p>● Upon termination of these Terms, your use of the Site any of the other CudiTrader Services or the Cryptocurrency Secured Loans or your relationship with CudiTrader, your obligations with respect to any outstanding Cryptocurrency Secured Loan shall continue without change and any provision which, by its nature or express terms should survive, will survive such termination or expiration, including, but not limited to, Sections 1, 2, 4.4, 4.5, 4.6, 5 and 9 – 11, 13 - 19.</p>
<h3>● 19.7 HEADINGS.</h3>
<p>● The heading references herein are for convenience purposes only, do not constitute a part of these Terms, and will not be deemed to limit or affect any of the provisions hereof.</p>
<h3>● 19.8 ENTIRE AGREEMENT.</h3>
<p>● These Terms, including the Privacy Policy, the Policies and the Loan Documents are the entire agreement between you and CudiTrader relating to the subject matter herein. These Terms and Policies will not be modified except by a change to these Terms or Policies made by CudiTrader as set forth in Section 8 above or as provided in the applicable agreement.</p>
<h3>● 19.9 NO AGENCY.</h3>
<p>● No agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is intended or created by these Terms.</p>
<h3>● 19.10 GEOGRAPHIC RESTRICTIONS</h3>
<p>● CudiTrader is based in the state of Lagos in the Nigeria and only provides Cryptocurrency Secured Loans in Nigeria. CudiTrader makes no claims that any of the CudiTrader Services, any Cryptocurrency Secured Loan or any of the content is accessible or appropriate outside of Nigeria. Access to the Site and the other CudiTrader Services, and the Cryptocurrency Secured Loans may not be legal by certain persons or in certain countries. If you access any of these CudiTrader Services from outside of Nigeria, you do so on your own initiative and are responsible for compliance with local laws and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against CudiTrader with respect there to.</p>
<h3>● 19.11 DISCLOSURES.</h3>
<p>● The Site and the other CudiTrader Services, and the Cryptocurrency Secured Loans are offered by Margin Tech International Investments Limited. located at: 11, Segun Maru Street Magodo Phase 1, Berger Lagos and email: info@cuditrader.com.</p>

	</div>
</div>